import { promises as fs } from 'fs';
import { existsSync } from 'fs';
import path from 'path';
import os from 'os';

/**
 * On-disk PreToolUse hook script the `claude` CLI runs for every tool
 * call. Receives the tool_name / tool_input / session_id on stdin,
 * POSTs to the backend (authenticated with `FASTOWL_PERMISSION_TOKEN`
 * out of the child's env), and writes the CLI's expected decision JSON
 * to stdout.
 *
 * CommonJS (`.cjs`) so it runs under any Node available on the host
 * without a transpile step. Kept deliberately dependency-free — uses
 * only `node:process` and global `fetch` (Node 18+).
 */
const HOOK_SCRIPT = `#!/usr/bin/env node
'use strict';
// fastowl PreToolUse permission hook (auto-generated by backend).
// Synchronously blocks the CLI's tool call until the backend returns
// an allow/deny decision. On any error, defaults to DENY so a broken
// backend never silently grants a dangerous tool.

const token = process.env.FASTOWL_PERMISSION_TOKEN;
const apiUrl = process.env.FASTOWL_API_URL;
const taskId = process.env.FASTOWL_TASK_ID || '';
const agentId = process.env.FASTOWL_AGENT_ID || '';

function writeDecision(decision, reason) {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: decision,
        permissionDecisionReason: reason || '',
      },
    })
  );
}

async function main() {
  if (!token || !apiUrl) {
    writeDecision('deny', 'fastowl hook misconfigured: no token or api url');
    return;
  }

  let buf = '';
  for await (const chunk of process.stdin) buf += chunk;

  let payload = {};
  try { payload = JSON.parse(buf || '{}'); } catch { payload = {}; }

  try {
    const res = await fetch(apiUrl + '/api/v1/permission-hook', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-fastowl-permission-token': token,
      },
      body: JSON.stringify({
        tool_name: payload.tool_name,
        tool_input: payload.tool_input,
        tool_use_id: payload.tool_use_id,
        session_id: payload.session_id,
        task_id: taskId,
        agent_id: agentId,
      }),
    });
    if (!res.ok) {
      writeDecision('deny', 'fastowl backend returned ' + res.status);
      return;
    }
    const data = await res.json();
    const decision = data && data.decision === 'allow' ? 'allow' : 'deny';
    writeDecision(decision, data && data.reason);
  } catch (err) {
    writeDecision('deny', 'fastowl hook error: ' + (err && err.message ? err.message : err));
  }
}

main();
`;

let cachedPath: string | null = null;

/**
 * Writes the hook script to a stable per-process path and returns it.
 * Idempotent — subsequent calls return the already-written path without
 * re-writing. Deleted on backend shutdown via `dispose()`.
 */
export async function ensurePermissionHook(): Promise<string> {
  if (cachedPath && existsSync(cachedPath)) return cachedPath;
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'fastowl-hook-'));
  const filePath = path.join(dir, 'permission.cjs');
  await fs.writeFile(filePath, HOOK_SCRIPT, { mode: 0o755 });
  cachedPath = filePath;
  return filePath;
}

export async function disposePermissionHook(): Promise<void> {
  if (!cachedPath) return;
  try {
    await fs.rm(path.dirname(cachedPath), { recursive: true, force: true });
  } catch {
    // Best effort — /tmp cleanup is OS-managed anyway.
  }
  cachedPath = null;
}
